spring:
  application:
    name: auth-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: quora_auth
      # authentication-database: admin
      # username: your_username
      # password: your_password

jwt:
  secret: ${JWT_SECRET:your_jwt_secret_key_which_should_be_at_least_256_bits_long}
  expiration: 86400000 # 24 hours in milliseconds

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true 