spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/quora
    elasticsearch:
      cluster-nodes: localhost:9200
      cluster-name: quora-cluster
  redis:
    host: localhost
    port: 6379

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ 