spring:
  application:
    name: question-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: quora_questions
    redis:
      host: localhost
      port: 6379
      # password: your_password
      timeout: 2000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: -1ms

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ 