spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

jwt:
  secret: ${JWT_SECRET:your_jwt_secret_key_which_should_be_at_least_256_bits_long}

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ 