spring:
  application:
    name: search-service
  elasticsearch:
    rest:
      uris: http://localhost:9200
      # username: your_username
      # password: your_password
      connection-timeout: 1s
      read-timeout: 1m
    
  data:
    redis:
      host: localhost
      port: 6379
      # password: your_password

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true