spring:
  application:
    name: eureka-server

server:
  port: 8761

# Logging configuration
logging:
  level:
    root: INFO
    com.quora.eureka: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
    org.springframework.boot.autoconfigure: DEBUG

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false 